_target_: torch.optim.lr_scheduler.CyclicLR
base_lr: 1e-3
max_lr: 1e-2
step_size_up: 2
step_size_down: 2
mode: 'triangular2'
gamma: 1.0
scale_mode: 'cycle'
cycle_momentum: False
base_momentum: 0.8
max_momentum: 0.9
last_epoch: -1
verbose: False
